In [7]:
!pip install numpy==1.26.4 pandas==2.2.2 scikit-learn==1.4.2 matplotlib seaborn mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting numpy==1.26.4
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Collecting pandas==2.2.2
  Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn==1.4.2
  Downloading scikit_learn-1.4.2-cp312-cp312-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: matplotlib in c:\users\vasis\appdata\roaming\python\python312\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: mlxtend in c:\users\vasis\appdata\roaming\python\python312\site-packages (0.24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from pandas==2.2.2) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from scikit-learn==1.4.2) (1.17.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from scikit-learn==1.4.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from scikit-learn==1.4.2) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
INFO: pip is looking at multiple versions of mlxtend to determine which version is compatible with other requirements. This could take a while.
Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB ? eta -:--:--
    --------------------------------------- 0.3/15.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.5 MB 524.3 kB/s eta 0:00:29
   -- ------------------------------------- 0.8/15.5 MB 621.2 kB/s eta 0:00:24
   -- ------------------------------------- 0.8/15.5 MB 621.2 kB/s eta 0:00:24
   -- ------------------------------------- 1.0/15.5 MB 739.8 kB/s eta 0:00:20
   ---- ----------------------------------- 1.6/15.5 MB 873.8 kB/s eta 0:00:16
   ---- ----------------------------------- 1.8/15.5 MB 958.5 kB/s eta 0:00:15
   ------ --------------------------------- 2.4/15.5 MB 1.1 MB/s eta 0:00:13
   ------ --------------------------------- 2.6/15.5 MB 1.1 MB/s eta 0:00:12
   -------- ------------------------------- 3.1/15.5 MB 1.2 MB/s eta 0:00:11
   -------- ------------------------------- 3.4/15.5 MB 1.3 MB/s eta 0:00:10
   ---------- ----------------------------- 3.9/15.5 MB 1.3 MB/s eta 0:00:09
   ---------- ----------------------------- 4.2/15.5 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 4.7/15.5 MB 1.4 MB/s eta 0:00:08
   ------------- -------------------------- 5.2/15.5 MB 1.5 MB/s eta 0:00:08
   -------------- ------------------------- 5.5/15.5 MB 1.5 MB/s eta 0:00:07
   --------------- ------------------------ 6.0/15.5 MB 1.5 MB/s eta 0:00:07
   ---------------- ----------------------- 6.6/15.5 MB 1.6 MB/s eta 0:00:06
   ------------------ --------------------- 7.1/15.5 MB 1.6 MB/s eta 0:00:06
   ------------------- -------------------- 7.6/15.5 MB 1.6 MB/s eta 0:00:05
   -------------------- ------------------- 8.1/15.5 MB 1.7 MB/s eta 0:00:05
   ---------------------- ----------------- 8.7/15.5 MB 1.7 MB/s eta 0:00:04
   ------------------------ --------------- 9.4/15.5 MB 1.8 MB/s eta 0:00:04
   ------------------------- -------------- 10.0/15.5 MB 1.8 MB/s eta 0:00:04
   --------------------------- ------------ 10.5/15.5 MB 1.9 MB/s eta 0:00:03
   ---------------------------- ----------- 11.0/15.5 MB 1.9 MB/s eta 0:00:03
   ----------------------------- ---------- 11.5/15.5 MB 1.9 MB/s eta 0:00:03
   ------------------------------- -------- 12.1/15.5 MB 1.9 MB/s eta 0:00:02
   -------------------------------- ------- 12.6/15.5 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 12.8/15.5 MB 1.9 MB/s eta 0:00:02
   ----------------------------------- ---- 13.6/15.5 MB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 13.9/15.5 MB 2.0 MB/s eta 0:00:01
   ------------------------------------- -- 14.4/15.5 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 14.9/15.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------  15.2/15.5 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 2.0 MB/s eta 0:00:00
Downloading pandas-2.2.2-cp312-cp312-win_amd64.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 3.3 MB/s eta 0:00:04
   --- ------------------------------------ 1.0/11.5 MB 3.0 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/11.5 MB 2.9 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/11.5 MB 2.3 MB/s eta 0:00:05
   --------- ------------------------------ 2.6/11.5 MB 2.5 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/11.5 MB 2.6 MB/s eta 0:00:04
   ------------- -------------------------- 3.9/11.5 MB 2.7 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.5 MB 2.7 MB/s eta 0:00:03
   ------------------ --------------------- 5.2/11.5 MB 2.8 MB/s eta 0:00:03
   -------------------- ------------------- 6.0/11.5 MB 2.9 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.5 MB 3.0 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.5 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.1/11.5 MB 3.0 MB/s eta 0:00:02
   ------------------------------ --------- 8.7/11.5 MB 3.0 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 10.0/11.5 MB 2.9 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.5 MB 2.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.7/11.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 2.8 MB/s eta 0:00:00
Downloading scikit_learn-1.4.2-cp312-cp312-win_amd64.whl (10.6 MB)
   ---------------------------------------- 0.0/10.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.6 MB 4.2 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/10.6 MB 3.0 MB/s eta 0:00:04
   ------ --------------------------------- 1.8/10.6 MB 3.0 MB/s eta 0:00:03
   -------- ------------------------------- 2.4/10.6 MB 3.1 MB/s eta 0:00:03
   ----------- ---------------------------- 3.1/10.6 MB 3.0 MB/s eta 0:00:03
   ------------- -------------------------- 3.7/10.6 MB 3.1 MB/s eta 0:00:03
   ---------------- ----------------------- 4.5/10.6 MB 3.1 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/10.6 MB 3.2 MB/s eta 0:00:02
   ---------------------- ----------------- 6.0/10.6 MB 3.2 MB/s eta 0:00:02
   -------------------------- ------------- 7.1/10.6 MB 3.4 MB/s eta 0:00:02
   ----------------------------- ---------- 7.9/10.6 MB 3.4 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.6 MB 3.4 MB/s eta 0:00:01
   ----------------------------------- ---- 9.4/10.6 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 10.0/10.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 10.6/10.6 MB 3.4 MB/s eta 0:00:00
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ----------------------- ---------------- 0.8/1.4 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 3.9 MB/s eta 0:00:00
Installing collected packages: numpy, pandas, scikit-learn, mlxtend
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.3
    Uninstalling numpy-2.4.3:
      Successfully uninstalled numpy-2.4.3
  Attempting uninstall: pandas
    Found existing installation: pandas 3.0.1
    Uninstalling pandas-3.0.1:
      Successfully uninstalled pandas-3.0.1
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.8.0
    Uninstalling scikit-learn-1.8.0:
      Successfully uninstalled scikit-learn-1.8.0
  Attempting uninstall: mlxtend
    Found existing installation: mlxtend 0.24.0
    Uninstalling mlxtend-0.24.0:
      Successfully uninstalled mlxtend-0.24.0
Successfully installed mlxtend-0.23.4 numpy-1.26.4 pandas-2.2.2 scikit-learn-1.4.2

  WARNING: The script f2py.exe is installed in 'C:\Users\vasis\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-mpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-mpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-ndas'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-learn'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.1.0 requires joblib~=1.0.1, but you have joblib 1.5.3 which is incompatible.
ydata-profiling 4.16.1 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.8 which is incompatible.
ydata-profiling 4.16.1 requires scipy<1.16,>=1.4.1, but you have scipy 1.17.1 which is incompatible.
ydata-profiling 4.16.1 requires visions[type_image_path]<0.8.2,>=0.7.5, but you have visions 0.7.4 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.

In [9]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
df = sns.load_dataset('iris')

In [13]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [17]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [19]:
df = df[['sepal_length', 'petal_length', 'species']]

In [21]:
df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [23]:
X = df.iloc[:, 0:2]
y = df.iloc[:, -1]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 40)

In [43]:
clf = LogisticRegression()

In [41]:
pip install numpy==1.26.4 pandas==2.2.2 scikit-learn==1.4.2 scipy==1.11.4 matplotlib seaborn mlxtend jupyter

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-ipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\~-ipy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.1.0 requires joblib~=1.0.1, but you have joblib 1.5.3 which is incompatible.
ydata-profiling 4.16.1 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.8 which is incompatible.
ydata-profiling 4.16.1 requires visions[type_image_path]<0.8.2,>=0.7.5, but you have visions 0.7.4 which is incompatible.

Requirement already satisfied: numpy==1.26.4 in c:\users\vasis\appdata\roaming\python\python312\site-packages (1.26.4)
Requirement already satisfied: pandas==2.2.2 in c:\users\vasis\appdata\roaming\python\python312\site-packages (2.2.2)
Requirement already satisfied: scikit-learn==1.4.2 in c:\users\vasis\appdata\roaming\python\python312\site-packages (1.4.2)
Collecting scipy==1.11.4
  Downloading scipy-1.11.4-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: matplotlib in c:\users\vasis\appdata\roaming\python\python312\site-packages (3.10.8)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: mlxtend in c:\users\vasis\appdata\roaming\python\python312\site-packages (0.23.4)
Requirement already satisfied: jupyter in c:\programdata\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from pandas==2.2.2) (2025.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from scikit-learn==1.4.2) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from scikit-learn==1.4.2) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: notebook in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.2.2)
Requirement already satisfied: qtconsole in c:\programdata\anaconda3\lib\site-packages (from jupyter) (5.5.1)
Requirement already satisfied: jupyter-console in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.16.4)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.28.0)
Requirement already satisfied: ipywidgets in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.8.1)
Requirement already satisfied: six>=1.5 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.6.7)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.27.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.6.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.9.0)
Requirement already satisfied: pyzmq>=24 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (25.1.2)
Requirement already satisfied: tornado>=6.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (6.4.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: ipython-genutils~=0.2.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.6 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (3.6.6)
Requirement already satisfied: jupyterlab-widgets<3,>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (1.0.0)
Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\programdata\anaconda3\lib\site-packages (from jupyter-console->jupyter) (3.0.43)
Requirement already satisfied: pygments in c:\programdata\anaconda3\lib\site-packages (from jupyter-console->jupyter) (2.15.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (4.12.3)
Requirement already satisfied: bleach!=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (4.1.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (3.1.4)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.1.2)
Requirement already satisfied: markupsafe>=2.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from nbconvert->jupyter) (2.0.1)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (2.0.4)
Requirement already satisfied: nbclient>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.8.0)
Requirement already satisfied: nbformat>=5.7 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (1.5.0)
Requirement already satisfied: tinycss2 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (1.2.1)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from notebook->jupyter) (2.14.1)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\programdata\anaconda3\lib\site-packages (from notebook->jupyter) (2.27.3)
Requirement already satisfied: jupyterlab<4.3,>=4.2.0 in c:\programdata\anaconda3\lib\site-packages (from notebook->jupyter) (4.2.5)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\programdata\anaconda3\lib\site-packages (from notebook->jupyter) (0.2.3)
Requirement already satisfied: qtpy>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from qtconsole->jupyter) (2.4.1)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (305.1)
Requirement already satisfied: anyio>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (4.2.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (21.3.0)
Requirement already satisfied: jupyter-events>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.10.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.4.4)
Requirement already satisfied: overrides>=5.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.14.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.10)
Requirement already satisfied: send2trash>=1.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (0.27.0)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2.2.0)
Requirement already satisfied: setuptools>=40.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab<4.3,>=4.2.0->notebook->jupyter) (75.1.0)
Requirement already satisfied: babel>=2.10 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2.11.0)
Requirement already satisfied: json5>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (0.9.6)
Requirement already satisfied: jsonschema>=4.18.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (4.23.0)
Requirement already satisfied: requests>=2.31 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2.32.3)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.7->nbconvert->jupyter) (2.16.2)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter) (0.2.5)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.5)
Requirement already satisfied: idna>=2.8 in c:\programdata\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (3.7)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (21.2.0)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter) (1.0.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab<4.3,>=4.2.0->notebook->jupyter) (0.14.0)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (0.10.6)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.0.7)
Requirement already satisfied: pyyaml>=5.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (6.0.1)
Requirement already satisfied: rfc3339-validator in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (0.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->notebook->jupyter) (2.2.3)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (2.0.5)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.2)
Requirement already satisfied: fqdn in c:\users\vasis\appdata\roaming\python\python312\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\vasis\appdata\roaming\python\python312\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\programdata\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.1)
Requirement already satisfied: uri-template in c:\users\vasis\appdata\roaming\python\python312\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\vasis\appdata\roaming\python\python312\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (24.11.1)
Requirement already satisfied: cffi>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->notebook->jupyter) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\programdata\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->notebook->jupyter) (1.2.3)
Downloading scipy-1.11.4-cp312-cp312-win_amd64.whl (43.7 MB)
   ---------------------------------------- 0.0/43.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/43.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/43.7 MB ? eta -:--:--
   ---------------------------------------- 0.3/43.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/43.7 MB 799.2 kB/s eta 0:00:55
    --------------------------------------- 0.8/43.7 MB 1.1 MB/s eta 0:00:40
    --------------------------------------- 1.0/43.7 MB 1.3 MB/s eta 0:00:34
   - -------------------------------------- 1.6/43.7 MB 1.5 MB/s eta 0:00:28
   - -------------------------------------- 2.1/43.7 MB 1.7 MB/s eta 0:00:26
   -- ------------------------------------- 2.6/43.7 MB 1.8 MB/s eta 0:00:23
   -- ------------------------------------- 3.1/43.7 MB 1.9 MB/s eta 0:00:22
   --- ------------------------------------ 3.7/43.7 MB 2.0 MB/s eta 0:00:21
   --- ------------------------------------ 4.2/43.7 MB 2.0 MB/s eta 0:00:20
   ---- ----------------------------------- 4.7/43.7 MB 2.1 MB/s eta 0:00:19
   ---- ----------------------------------- 5.2/43.7 MB 2.1 MB/s eta 0:00:19
   ----- ---------------------------------- 5.8/43.7 MB 2.2 MB/s eta 0:00:18
   ----- ---------------------------------- 6.6/43.7 MB 2.2 MB/s eta 0:00:17
   ------ --------------------------------- 7.1/43.7 MB 2.3 MB/s eta 0:00:17
   ------ --------------------------------- 7.6/43.7 MB 2.3 MB/s eta 0:00:16
   ------- -------------------------------- 8.4/43.7 MB 2.3 MB/s eta 0:00:16
   -------- ------------------------------- 8.9/43.7 MB 2.4 MB/s eta 0:00:15
   -------- ------------------------------- 9.7/43.7 MB 2.4 MB/s eta 0:00:15
   --------- ------------------------------ 10.5/43.7 MB 2.5 MB/s eta 0:00:14
   ---------- ----------------------------- 11.3/43.7 MB 2.5 MB/s eta 0:00:13
   ---------- ----------------------------- 11.8/43.7 MB 2.6 MB/s eta 0:00:13
   ----------- ---------------------------- 12.6/43.7 MB 2.6 MB/s eta 0:00:13
   ------------ --------------------------- 13.4/43.7 MB 2.7 MB/s eta 0:00:12
   ------------ --------------------------- 14.2/43.7 MB 2.7 MB/s eta 0:00:11
   ------------- -------------------------- 14.9/43.7 MB 2.7 MB/s eta 0:00:11
   -------------- ------------------------- 15.7/43.7 MB 2.8 MB/s eta 0:00:11
   --------------- ------------------------ 16.5/43.7 MB 2.8 MB/s eta 0:00:10
   --------------- ------------------------ 17.3/43.7 MB 2.8 MB/s eta 0:00:10
   ---------------- ----------------------- 18.4/43.7 MB 2.9 MB/s eta 0:00:09
   ----------------- ---------------------- 19.1/43.7 MB 2.9 MB/s eta 0:00:09
   ------------------ --------------------- 19.9/43.7 MB 3.0 MB/s eta 0:00:09
   ------------------ --------------------- 20.7/43.7 MB 3.0 MB/s eta 0:00:08
   ------------------- -------------------- 21.8/43.7 MB 3.0 MB/s eta 0:00:08
   -------------------- ------------------- 22.5/43.7 MB 3.1 MB/s eta 0:00:07
   --------------------- ------------------ 23.6/43.7 MB 3.1 MB/s eta 0:00:07
   ---------------------- ----------------- 24.6/43.7 MB 3.2 MB/s eta 0:00:07
   ----------------------- ---------------- 25.7/43.7 MB 3.2 MB/s eta 0:00:06

In [45]:
clf.fit(X_train, y_train)

ImportError: cannot import name 'is_scalar_nan' from 'sklearn.utils' (C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\__init__.py)

ImportError: cannot import name 'is_scalar_nan' from 'sklearn.utils' (C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\__init__.py)

ImportError: cannot import name 'is_scalar_nan' from 'sklearn.utils' (C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\__init__.py)

In [ ]:
y_pred = clf.predict(X_test)

In [31]:
print(accuracy_score(y_test, y_pred))

NameError: name 'y_pred' is not defined

In [83]:
pd.DataFrame(confusion_matrix(y_test, y_pred))

   0   1  2
0  8   0  0
1  0  12  0
2  0   1  9

In [85]:
query = np.array([[3.4, 2.7]])
clf.predict_proba(query)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[8.30553282e-01, 1.68801162e-01, 6.45555426e-04]])

In [87]:

clf.predict(query)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [1]:
from mlxtend.plotting import plot_decision_regions
plot_decision_regions(X.values, y.values, clf, legend=2)

# Adding axes annotations
plt.xlabel('sepal length [cm]')
plt.ylabel('petal length [cm]')
plt.title('Softmax on Iris')

plt.show()

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vasis\AppData\Local\Temp\ipykernel_18820\3726608533.py", line 1, in <module>
    from mlxtend.plotting import plot_decision_regions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\__init__.py", line 10, in <module>
    from .enrichment_plot import enrichment_plot
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\enrichment_plot.py", line 14, in <module>
    import pandas as pd
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 34, in <module>
    from pandas.compat import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\compat\__init__.py", line 28, in <module>
    from pandas.compat.pyarrow import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\compat\pyarrow.py", line 12, in <module>
    import pyarrow as pa
  File "C:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vasis\AppData\Local\Temp\ipykernel_18820\3726608533.py", line 1, in <module>
    from mlxtend.plotting import plot_decision_regions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\__init__.py", line 10, in <module>
    from .enrichment_plot import enrichment_plot
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\enrichment_plot.py", line 14, in <module>
    import pandas as pd
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\dtypes\dtypes.py", line 28, in <module>
    from pandas._libs import (
  File "C:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vasis\AppData\Local\Temp\ipykernel_18820\3726608533.py", line 1, in <module>
    from mlxtend.plotting import plot_decision_regions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\__init__.py", line 10, in <module>
    from .enrichment_plot import enrichment_plot
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\enrichment_plot.py", line 14, in <module>
    import pandas as pd
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 65, in <module>
    from pandas.core import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\__init__.py", line 9, in <module>
    from pandas.core.ops.array_ops import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\ops\array_ops.py", line 55, in <module>
    from pandas.core.computation import expressions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\expressions.py", line 22, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\computation\check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\anaconda3\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vasis\AppData\Local\Temp\ipykernel_18820\3726608533.py", line 1, in <module>
    from mlxtend.plotting import plot_decision_regions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\__init__.py", line 10, in <module>
    from .enrichment_plot import enrichment_plot
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\enrichment_plot.py", line 14, in <module>
    import pandas as pd
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\__init__.py", line 58, in <module>
    from pandas.core.api import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\api.py", line 27, in <module>
    from pandas.core.arrays import Categorical
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\arrow\array.py", line 79, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\arrays\masked.py", line 56, in <module>
    from pandas.core import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\core\nanops.py", line 54, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\pandas\compat\_optional.py", line 158, in import_optional_dependency
    module = importlib.import_module(name)
  File "C:\ProgramData\anaconda3\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\ProgramData\anaconda3\Lib\site-packages\bottleneck\__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\ProgramData\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\Lib\asyncio\base_events.py", line 1986, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell
    result = self._run_cell(
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell
    result = runner(coro)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner
    coro.send(None)
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\ProgramData\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\vasis\AppData\Local\Temp\ipykernel_18820\3726608533.py", line 1, in <module>
    from mlxtend.plotting import plot_decision_regions
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\__init__.py", line 13, in <module>
    from .pca_correlation_graph import plot_pca_correlation_graph
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\plotting\pca_correlation_graph.py", line 11, in <module>
    from mlxtend.feature_extraction import PrincipalComponentAnalysis
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\feature_extraction\__init__.py", line 7, in <module>
    from .linear_discriminant_analysis import LinearDiscriminantAnalysis
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\feature_extraction\linear_discriminant_analysis.py", line 11, in <module>
    from .._base import _BaseModel
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\_base\__init__.py", line 8, in <module>
    from ._classifier import _Classifier
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\mlxtend\_base\_classifier.py", line 12, in <module>
    from sklearn.utils._tags import ClassifierTags, Tags, TargetTags
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\__init__.py", line 70, in <module>
    from sklearn.base import clone  # noqa: E402
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py", line 19, in <module>
    from sklearn.utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\__init__.py", line 9, in <module>
    from sklearn.utils._chunking import gen_batches, gen_even_slices
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\_chunking.py", line 11, in <module>
    from sklearn.utils._param_validation import Interval, validate_params
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\_param_validation.py", line 17, in <module>
    from sklearn.utils.validation import _is_arraylike_not_scalar
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\validation.py", line 24, in <module>
    from sklearn.utils._array_api import (
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\_array_api.py", line 20, in <module>
    from sklearn.utils.fixes import parse_version
  File "C:\Users\vasis\AppData\Roaming\Python\Python312\site-packages\sklearn\utils\fixes.py", line 389, in <module>
    import pyarrow
  File "C:\ProgramData\anaconda3\Lib\site-packages\pyarrow\__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

ImportError:
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

ImportError: numpy.core.multiarray failed to import

In [97]:
import sys
!{sys.executable} -m pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Using cached mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)
Collecting scipy>=1.16.3 (from mlxtend)
  Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting numpy>=2.3.5 (from mlxtend)
  Downloading numpy-2.4.3-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting pandas>=2.3.3 (from mlxtend)
  Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting joblib>=1.5.2 (from mlxtend)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
INFO: pip is looking at multiple versions of contourpy to determine which version is compatible with other requirements. This could take a while.
Collecting contourpy>=1.0.1 (from matplotlib>=3.10.8->mlxtend)
  Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.16.0)
Using cached mlxtend-0.24.0-py3-none-any.whl (1.4 MB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ----- ---------------------------------- 1.0/8.1 MB 5.0 MB/s eta 0:00:02
   -------------- ------------------------- 2.9/8.1 MB 7.3 MB/s eta 0:00:01
   ----------------------- ---------------- 4.7/8.1 MB 7.7 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.1 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 8.4 MB/s eta 0:00:00
Downloading numpy-2.4.3-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.3 MB 8.3 MB/s eta 0:00:02
   ------------ --------------------------- 3.9/12.3 MB 9.8 MB/s eta 0:00:01
   ---------------------- ----------------- 6.8/12.3 MB 11.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.7/12.3 MB 11.0 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 10.6 MB/s eta 0:00:00
Downloading pandas-3.0.1-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   -------- ------------------------------- 2.1/9.7 MB 10.7 MB/s eta 0:00:01
   ------------------------------- -------- 7.6/9.7 MB 18.0 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 16.4 MB/s eta 0:00:00
Downloading scikit_learn-1.8.0-cp312-cp312-win_amd64.whl (8.0 MB)
   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--
   ---------- ----------------------------- 2.1/8.0 MB 11.7 MB/s eta 0:00:01
   -------------------- ------------------- 4.2/8.0 MB 10.5 MB/s eta 0:00:01
   -------------------------------- ------- 6.6/8.0 MB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 8.0/8.0 MB 9.7 MB/s eta 0:00:00
Downloading scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
   ---------------------------------------- 0.0/36.5 MB ? eta -:--:--
   -- ------------------------------------- 2.4/36.5 MB 12.2 MB/s eta 0:00:03
   ---- ----------------------------------- 4.5/36.5 MB 11.2 MB/s eta 0:00:03
   -------- ------------------------------- 7.3/36.5 MB 11.6 MB/s eta 0:00:03
   ----------- ---------------------------- 10.5/36.5 MB 12.6 MB/s eta 0:00:03
   ---------------- ----------------------- 14.9/36.5 MB 14.2 MB/s eta 0:00:02
   -------------------- ------------------- 18.4/36.5 MB 14.6 MB/s eta 0:00:02
   ----------------------- ---------------- 21.5/36.5 MB 14.8 MB/s eta 0:00:02
   -------------------------- ------------- 23.9/36.5 MB 14.2 MB/s eta 0:00:01
   ---------------------------- ----------- 26.5/36.5 MB 14.2 MB/s eta 0:00:01
   -------------------------------- ------- 29.4/36.5 MB 14.0 MB/s eta 0:00:01
   ----------------------------------- ---- 32.2/36.5 MB 13.9 MB/s eta 0:00:01
   -------------------------------------- - 35.1/36.5 MB 14.1 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.5 MB 13.8 MB/s eta 0:00:01
   ---------------------------------------- 36.5/36.5 MB 13.3 MB/s eta 0:00:00
Downloading contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Installing collected packages: numpy, joblib, scipy, pandas, contourpy, scikit-learn, matplotlib, mlxtend
  Attempting uninstall: joblib
    Found existing installation: joblib 1.0.1
    Uninstalling joblib-1.0.1:
      Successfully uninstalled joblib-1.0.1
Successfully installed contourpy-1.3.3 joblib-1.5.3 matplotlib-3.10.8 mlxtend-0.24.0 numpy-2.4.3 pandas-3.0.1 scikit-learn-1.8.0 scipy-1.17.1

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\vasis\AppData\Roaming\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.1.0 requires joblib~=1.0.1, but you have joblib 1.5.3 which is incompatible.
ydata-profiling 4.16.1 requires matplotlib<=3.10,>=3.5, but you have matplotlib 3.10.8 which is incompatible.
ydata-profiling 4.16.1 requires numpy<2.2,>=1.16.0, but you have numpy 2.4.3 which is incompatible.
ydata-profiling 4.16.1 requires pandas!=1.4.0,<3.0,>1.1, but you have pandas 3.0.1 which is incompatible.
ydata-profiling 4.16.1 requires scipy<1.16,>=1.4.1, but you have scipy 1.17.1 which is incompatible.
ydata-profiling 4.16.1 requires visions[type_image_path]<0.8.2,>=0.7.5, but you have visions 0.7.4 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.4.3 which is incompatible.
gensim 4.3.3 requires scipy<1.14.0,>=1.7.0, but you have scipy 1.17.1 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.3 which is incompatible.
streamlit 1.37.1 requires pandas<3,>=1.3.0, but you have pandas 3.0.1 which is incompatible.